name: build c++20

on:
  push:
  pull_request:

jobs:
  build-gcc-cpp20:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt install gcc-10 g++-10
    - name: make
      run: make COMPILER=g++-10 STD=c++20
    - name: build basic test
      working-directory: tests
      run: make basic_test COMPILER=g++-10 STD=c++20
  build-clang-cpp20:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make COMPILER=clang++ STD=c++20
    - name: build basic test
      working-directory: tests
      run: make basic_test COMPILER=clang++ STD=c++20
  build-msvc-cpp20:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.10.0
    - name: make
      run: make COMPILER=msvc STD=c++20
    - name: build basic test
      working-directory: tests
      run: make basic_test COMPILER=msvc STD=c++20
  build-gcc-windows-cpp20:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: update mingw
      run: choco upgrade mingw
    - name: make
      run: make COMPILER=g++ STD=c++20
    - name: build basic test
      working-directory: tests
      run: make basic_test COMPILER=g++ STD=c++20
  build-clang-windows-cpp20:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make COMPILER=clang++ STD=c++20
    - name: build basic test
      working-directory: tests
      run: make basic_test COMPILER=clang++ STD=c++20
