name: clang-tidy

on:
  push:
  pull_request:

jobs:
  clang-tidy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt install clang-tidy
    - name: clang-tidy
      run: |
           status=0
           while read f
           do
               echo checking $f
               clang-tidy $f -- -std=c++17 -Iinclude
               ret=$?
               if [ $ret -ne 0 ]; then
                   status=1
               fi
           done <<< $(find include src tests -name "*.hpp" -o -name "*.cpp")
           exit $status
